### ISSUE TITLE
A PHP Error was encountered !

### ISSUE THREAD

**Issue by arkarkyaw88** [sylvacoin/elibrary#1]
A PHP Error was encountered
Severity: 8192

Message: The each() function is deprecated. This message will be suppressed on further calls

Filename: MX/Modules.php

Line Number: 83

Backtrace:

File: C:\xampp\htdocs\elibrary\application\third_party\MX\Modules.php
Line: 83
Function: each

File: C:\xampp\htdocs\elibrary\application\third_party\MX\Loader.php
Line: 251
Function: load

File: C:\xampp\htdocs\elibrary\application\third_party\MX\Loader.php
Line: 258
Function: module

File: C:\xampp\htdocs\elibrary\application\third_party\MX\Loader.php
Line: 248
Function: modules

File: C:\xampp\htdocs\elibrary\application\modules\auth\controllers\Auth.php
Line: 11
Function: module

File: C:\xampp\htdocs\elibrary\index.php

**Comment by sylvacoin** [comment]
Sorry about the delay have fixed the issue. Had to do with the version of PHP.

**Comment by sylvacoin** [comment]
Must apologize for the delay. **But issue has been fixed!** 
_Had to do with PHP 7.2 update which discontinued the use of each() function which was used in Modules.php._
